name: Merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  cherry_pick_job:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/cherry-pick.yml
